api_platform:
    title: 'Cashbox API'
    description: 'Modern API for penalty and contribution management'
    version: '1.1.0'
    
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization']
            max_age: 0
        pagination:
            items_per_page: 20
            maximum_items_per_page: 100
            client_items_per_page: true
    
    # OpenAPI/Swagger documentation
    openapi:
        contact:
            name: 'Cashbox API Team'
            email: 'api@cashbox.local'
        
    # Supported formats
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        csv: ['text/csv']
        
    # Error formats  
    error_formats:
        jsonproblem: ['application/problem+json']
        jsonld: ['application/ld+json']
        
    # Mapping
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']