lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # Token-Gültigkeit: 1 Stunde
    user_identity_field: emailValue # Feld zur Benutzeridentifikation
    clock_skew: 0
    token_extractors:
        authorization_header:      # Token aus Authorization-Header extrahieren
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:                    # Token aus Cookie extrahieren (optional)
            enabled: true
            name: BEARER
