# Rate limiting configuration - disabled until dependencies are resolved
# framework:
#     rate_limiter:
#         # Login attempt limiting - prevent brute force attacks
#         login_attempts:
#             policy: 'sliding_window'
#             limit: 5
#             interval: '15 minutes'
#             
#         # API request limiting - prevent abuse
#         api_requests:
#             policy: 'token_bucket'
#             limit: 100
#             interval: '1 hour'
#             
#         # Registration limiting - prevent spam
#         registration:
#             policy: 'fixed_window'
#             limit: 3
#             interval: '1 hour'