
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: ${DOCKER_PHP_TARGET:-php_dev}
    container_name: cashbox_php
    profiles: ["default", "dev", "test"]
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@database:5432/cashbox_db?serverVersion=16&charset=utf8
    ports:
      - "8080:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  cli:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: ${DOCKER_PHP_TARGET:-php_dev}
    container_name: cashbox_cli
    profiles: ["default", "dev", "test"]
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@database:5432/cashbox_db?serverVersion=16&charset=utf8
    command: ["tail", "-f", "/dev/null"]

  database:
    image: postgres:16-alpine
    container_name: cashbox_database
    profiles: ["default", "dev", "test"]
    environment:
      POSTGRES_DB: cashbox_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-md5}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "cashbox_db", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # Adminer für Datenbankmanagement (nur für Entwicklung)
  adminer:
    image: adminer:latest
    container_name: cashbox_adminer
    profiles: ["dev"]
    ports:
      - "8081:8080"
    depends_on:
      - database

  # Test-Runner für automatisierte Tests
  test_runner:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php_dev
    container_name: cashbox_test_runner
    working_dir: /var/www
    volumes:
      - ./:/var/www
    profiles: ["test"]
    environment:
      - APP_ENV=test
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@database:5432/cashbox_test?serverVersion=16&charset=utf8
    command: ["./docker/php/run-tests.sh"]
    depends_on:
      database:
        condition: service_healthy

volumes:
  database_data:
