
services:
  php:
    image: php:8.4-fpm-alpine
    container_name: cashbox_php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - database
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8
    command: >
      sh -c "apk add --no-cache git unzip libpq-dev postgresql-dev &&
             docker-php-ext-install pdo pdo_pgsql &&
             curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
             composer require ramsey/uuid-doctrine --no-interaction &&
             composer install --no-interaction &&
             php bin/console doctrine:schema:update --force --no-interaction &&
             php -S 0.0.0.0:8000 -t public/"
    ports:
      - "8080:8000"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: cashbox_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
